services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Désactive la sécurité pour simplifier
      - ES_JAVA_OPTS=-Xms2g -Xmx2g   # Configuration mémoire
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - shared_data:/github-repo-recommendation/services/git_api  
    restart: unless-stopped  # Redémarre automatiquement sauf si manuellement arrêté
    networks:
      - esnet

  api_bdd:
    build:
      context: ./services/api_bdd
      dockerfile: Dockerfile
    container_name: api_bdd
    depends_on:
      - elasticsearch
      - git_api
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - shared_data:/github-repo-recommendation/services/git_api
      - ./data/processed/github_repos.json:/app/data/processed/github_repos.json
    networks:
      - esnet

  git_api:
    build:
      context: ./services/git_api
      dockerfile: Dockerfile
    container_name: git_api
    depends_on:
      - elasticsearch
    volumes:
      - shared_data:/github-repo-recommendation/services/git_api 
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5602:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9201
    restart: unless-stopped

networks:
  esnet:
    driver: bridge

volumes:
  es_data:
    driver: local
  shared_data:
    driver: local